#sabnzbd
---
- include_role:
    name: variables

- name: Remove sabnzbd Container
  docker_container:
    name: sabnzbd
    state: absent

- name: Creates directory
  file:
    path: "{{path.stdout}}/tools/sabnzbd"
    state: directory
    owner: 1000
    group: 1000
    mode: 0775
    recurse: yes

- name: Deploy sabnzbd Container
  docker_container:
    name: sabnzbd
    image: linuxserver/sabnzbd
    pull: yes
    cpu_shares: 512
    published_ports:
      - "8080:8080"
    volumes:
      - "{{path.stdout}}/tools/sabnzbd:/config"
      - "{{path.stdout}}/downloads/sab/complete:/downloads"
      - "{{path.stdout}}/downloads/sab/incomplete:/incomplete-downloads"
      - /etc/localtime:/etc/localtime:ro
    env:
      PUID: "1000"
      PGID: "1000"
    networks:
      - name: toolbox
        aliases:
          - sabnzbd
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      # traefik.frontend.auth.basic: "{{username.stdout}}:{{password.stdout}}"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:sabnzbd.{{domain.stdout}}"
      traefik.port: "8080"
      traefik.docker.network: "toolbox"
