#sonarr
---
- include_role:
    name: variables

- name: Remove sonarr Container
  docker_container:
    name: sonarr
    state: absent

- name: Creates directory
  file:
    path: "{{path.stdout}}/tools/sonarr"
    state: directory
    owner: 1000
    group: 1000
    mode: 0775
    recurse: yes

- name: Deploy sonarr Container
  docker_container:
    name: sonarr
    image: hotio/suitarr
    pull: yes
    cpu_shares: 1024
    published_ports:
      - "8989:8989"
    volumes:
      - "{{path.stdout}}/tools/sonarr:/config"
      - /etc/localtime:/etc/localtime:ro
      - "{{path.stdout}}/downloads/sab/complete:/complete"
      - "{{path.stdout}}/rutorrents:/downloads"
    env:
      PUID: "1000"
      PGID: "1000"
      UMASK: "022"
      VERSION: "stable"
      APP: "sonarr"
      BACKUP: "yes"
    networks:
      - name: toolbox
        aliases:
          - sonarr
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      # traefik.frontend.auth.basic: "{{username.stdout}}:{{password.stdout}}"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:sonarr.{{domain.stdout}}"
      traefik.port: "8989"
      traefik.docker.network: "toolbox"
