#portainer
---
- include_role:
    name: variables

- name: Remove portainer Container
  docker_container:
    name: portainer
    state: absent

- name: Creates directory
  file:
    path: "{{path.stdout}}/tools/portainer"
    state: directory
    owner: 1000
    group: 1000
    mode: 0775
    recurse: yes

- name: Deploy Portainer Container
  docker_container:
    name: portainer
    image: portainer/portainer
    pull: yes
    cpu_shares: 512
    published_ports:
      - "9000:9000"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
     - "{{path.stdout}}/tools/portainer:/data"
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - name: toolbox
        aliases:
          - portainer
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:portainer.{{domain.stdout}}, config.{{domain.stdout}}"
      traefik.port: "9000"
      traefik.docker.network: "toolbox"