#ombi
---
- include_role:
    name: variables

- name: Remove ombi Container
  docker_container:
    name: ombi
    state: absent

- name: Deploy ombi Container
  docker_container:
    name: ombi
    image: linuxserver/ombi
    pull: yes
    cpu_shares: 1024
    published_ports:
      - "3579:3579"
    volumes:
      - "{{path.stdout}}tools/ombi:/config"
      - /etc/localtime:/etc/localtime:ro
    env:
      PUID: "1000"
      PGID: "1000"
    networks:
      - name: toolbox
        aliases:
          - ombi
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      # traefik.frontend.auth.basic: "{{username.stdout}}:{{password.stdout}}"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:ombi.{{domain.stdout}}, wishlist.{{domain.stdout}},requests.{{domain.stdout}}"
      traefik.port: "3579"
